"""
共享数据模型包 / Shared data models package.

向后兼容：所有 `from engines.shared.models import X` 的导入继续有效。
Backward-compatible re-export of all public names from sub-modules.
"""

# ---------------------------------------------------------------------------
# core: enumerations and foundational types
# ---------------------------------------------------------------------------
from engines.shared.models.core import (
    AccessDomain,
    AdmissibilityStatus,
    AgentRole,
    AttackStrength,
    AuthenticityRisk,
    BlockingConditionType,
    BurdenStatus,
    CaseType,
    ChangeItemObjectType,
    ClaimType,
    ContractValidity,
    DiffDirection,
    DisputeResolutionStatus,
    EvidenceStatus,
    EvidenceStrength,
    EvidenceType,
    ImpactTarget,
    IssueCategory,
    IssueStatus,
    IssueType,
    JobStatus,
    LegalityRisk,
    LLMClient,
    OutcomeImpact,
    OutcomeImpactSize,
    Perspective,
    PracticallyObtainable,
    ProbativeValue,
    ProcedurePhase,
    ProcedureState,
    PromptProfile,
    PropositionStatus,
    RawMaterial,
    RecommendedAction,
    RelevanceScore,
    RepaymentAttribution,
    RiskImpactObject,
    ScenarioStatus,
    StatementClass,
    SupplementCost,
    Vulnerability,
    WorkflowStage,
)

# ---------------------------------------------------------------------------
# analysis: case objects, report artifacts, adversarial and analysis models
# ---------------------------------------------------------------------------
from engines.shared.models.analysis import (
    ActionRecommendation,
    AgentOutput,
    AlternativeClaimSuggestion,
    Burden,
    Claim,
    ClaimAbandonSuggestion,
    ClaimAmendmentSuggestion,
    ClaimDecomposition,
    ClaimIssueMapping,
    ConfidenceMetrics,
    ConsistencyCheckResult,
    CredibilityDeduction,
    CredibilityScorecard,
    Defense,
    DefenseIssueMapping,
    Evidence,
    EvidenceGapItem,
    EvidenceIndex,
    ExecutiveSummaryArtifact,
    ExecutiveSummaryStructuredOutput,
    FactProposition,
    InteractionTurn,
    InternalDecisionSummary,
    Issue,
    IssueTree,
    KeyConclusion,
    LitigationHistory,
    PartyActionPlan,
    Party,
    ReportArtifact,
    ReportSection,
    RiskFlag,
    StrategicRecommendation,
    TrialExplanationPriority,
)

# ---------------------------------------------------------------------------
# pipeline: infrastructure, job/run, financial, decision tree, attack chain
# ---------------------------------------------------------------------------
from engines.shared.models.pipeline import (
    AmountCalculationReport,
    AmountConflict,
    AmountConsistencyCheck,
    ArtifactRef,
    AttackNode,
    BlockingCondition,
    ClaimCalculationEntry,
    ConfidenceInterval,
    DecisionPath,
    DecisionPathTree,
    DisputedAmountAttribution,
    ExtractionMetadata,
    InputSnapshot,
    InterestRecalculation,
    Job,
    JobError,
    LoanTransaction,
    MaterialRef,
    OptimalAttackChain,
    PathRankingItem,
    RepaymentTransaction,
    Run,
)

# ---------------------------------------------------------------------------
# protocol: scenario layer
# ---------------------------------------------------------------------------
from engines.shared.models.protocol import (
    ChangeItem,
    DiffEntry,
    Scenario,
)

__all__ = [
    # core
    "AccessDomain",
    "AdmissibilityStatus",
    "AgentRole",
    "AttackStrength",
    "AuthenticityRisk",
    "BlockingConditionType",
    "BurdenStatus",
    "CaseType",
    "ChangeItemObjectType",
    "ClaimType",
    "ContractValidity",
    "DiffDirection",
    "DisputeResolutionStatus",
    "EvidenceStatus",
    "EvidenceStrength",
    "EvidenceType",
    "ImpactTarget",
    "IssueCategory",
    "IssueStatus",
    "IssueType",
    "JobStatus",
    "LegalityRisk",
    "LLMClient",
    "OutcomeImpact",
    "OutcomeImpactSize",
    "Perspective",
    "PracticallyObtainable",
    "ProbativeValue",
    "ProcedurePhase",
    "ProcedureState",
    "PromptProfile",
    "PropositionStatus",
    "RawMaterial",
    "RecommendedAction",
    "RelevanceScore",
    "RepaymentAttribution",
    "RiskImpactObject",
    "ScenarioStatus",
    "StatementClass",
    "SupplementCost",
    "Vulnerability",
    "WorkflowStage",
    # analysis
    "ActionRecommendation",
    "AgentOutput",
    "AlternativeClaimSuggestion",
    "Burden",
    "Claim",
    "ClaimAbandonSuggestion",
    "ClaimAmendmentSuggestion",
    "ClaimDecomposition",
    "ClaimIssueMapping",
    "ConfidenceMetrics",
    "ConsistencyCheckResult",
    "CredibilityDeduction",
    "CredibilityScorecard",
    "Defense",
    "DefenseIssueMapping",
    "Evidence",
    "EvidenceGapItem",
    "EvidenceIndex",
    "ExecutiveSummaryArtifact",
    "ExecutiveSummaryStructuredOutput",
    "FactProposition",
    "InteractionTurn",
    "InternalDecisionSummary",
    "Issue",
    "IssueTree",
    "KeyConclusion",
    "LitigationHistory",
    "Party",
    "PartyActionPlan",
    "ReportArtifact",
    "ReportSection",
    "RiskFlag",
    "StrategicRecommendation",
    "TrialExplanationPriority",
    # pipeline
    "AmountCalculationReport",
    "AmountConflict",
    "AmountConsistencyCheck",
    "ArtifactRef",
    "AttackNode",
    "BlockingCondition",
    "ClaimCalculationEntry",
    "ConfidenceInterval",
    "DecisionPath",
    "DecisionPathTree",
    "DisputedAmountAttribution",
    "ExtractionMetadata",
    "InputSnapshot",
    "InterestRecalculation",
    "Job",
    "JobError",
    "LoanTransaction",
    "MaterialRef",
    "OptimalAttackChain",
    "PathRankingItem",
    "RepaymentTransaction",
    "Run",
    # protocol
    "ChangeItem",
    "DiffEntry",
    "Scenario",
]
